app {
  kafka {
    bootstrap-servers = "localhost:9092"
    bootstrap-servers = ${?KAFKA_BOOTSTRAP_SERVERS}
    topic            = "discord-messages"
    topic            = ${?KAFKA_TOPIC}
  }

  producer {
    dataset-path = "data/messages.csv"
    dataset-path = ${?DATASET_PATH}
    batch-size   = 100
    batch-size   = ${?PRODUCER_BATCH_SIZE}
    batch-delay-ms = 1000
    batch-delay-ms = ${?PRODUCER_BATCH_DELAY_MS}
  }

  consumer {
    output-base-path = "data/output"
    output-base-path = ${?OUTPUT_BASE_PATH}

    word-counts-path     = ${app.consumer.output-base-path}"/word_counts"
    monthly-counts-path  = ${app.consumer.output-base-path}"/monthly_counts"
    user-stats-path      = ${app.consumer.output-base-path}"/user_stats"
    checkpoint-base-path = ${app.consumer.output-base-path}"/checkpoints"

    watermark-delay = "10 minutes"
    stopwords-path  = "src/main/resources/stopwords-fr.txt"
    stopwords-path  = ${?STOPWORDS_PATH}
  }

  spark {
    app-name           = "DiscordStreamProcessor"
    master             = "local[*]"
    shuffle-partitions = 4
  }
}
